DROP DATABASE IF EXISTS statsdb;
CREATE DATABASE IF NOT EXISTS statsdb;
USE statsdb;

CREATE TABLE Users
(Username VARCHAR(30),
Name VARCHAR(30),
Password VARCHAR(30),
CONSTRAINT pk_Username PRIMARY KEY (Username)
);

CREATE TABLE Uploads
(fID INT,
Username VARCHAR(30),
File LONGBLOB,
Filename VARCHAR(30),
CONSTRAINT PK_fID PRIMARY KEY (fID)
CONSTRAINT FK_Username FOREIGN KEY (Username)
REFERENCES Users(Username)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET utf8 COLLATE = utf8_general_ci;;
